disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing

included:
  - Sources

excluded:
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
